name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TOKEN: ${{secrets.TOKEN}}

jobs:
  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4
    - name: deploy
      run: cargo build
